name: testing

on:
  push:
    paths:
      - 'python/**'
  pull_request:
    paths:
      - 'python/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Linter checks
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: cd python && pip install -e .[compute_resource]
    - name: Install packages needed for tests
      run: pip install pytest pytest-asyncio pytest-cov pyright boto3 kachery_cloud flake8
    - name: Install additional packages used by api_helpers
      run: cd python && pip install -e .[api]
    - name: Run linter checks
      run: cd python && flake8 --config ../.flake8 && pyright